// This file is auto-generated by @hey-api/openapi-ts

import type {
    Client,
    Options as Options2,
    TDataShape
} from './client';
import {
    client
} from './client.gen';
import type {
    CheckGuildApiData,
    CheckGuildApiErrors,
    CheckGuildApiResponses,
    DeleteApiDiscordByGuildIdData,
    DeleteApiDiscordByGuildIdErrors,
    DeleteApiDiscordByGuildIdResponses,
    DeleteApiGamesByGameIdDeleteData,
    DeleteApiGamesByGameIdDeleteErrors,
    DeleteApiGamesByGameIdDeleteResponses,
    GetApiDiscordByGuildIdOccupancyData,
    GetApiDiscordByGuildIdOccupancyErrors,
    GetApiDiscordByGuildIdOccupancyResponses,
    GetApiDiscordByGuildIdStatusData,
    GetApiDiscordByGuildIdStatusErrors,
    GetApiDiscordByGuildIdStatusResponses,
    GetApiGamesByGameIdData,
    GetApiGamesByGameIdErrors,
    GetApiGamesByGameIdResponses,
    GetApiGamesData,
    GetApiGamesErrors,
    GetApiGamesResponses,
    GetApiRolesData,
    GetApiRolesResponses,
    PostApiDiscordByGuildIdByUserIdData,
    PostApiDiscordByGuildIdByUserIdErrors,
    PostApiDiscordByGuildIdByUserIdResponses,
    PostApiDiscordByGuildIdData,
    PostApiDiscordByGuildIdErrors,
    PostApiDiscordByGuildIdRebuildData,
    PostApiDiscordByGuildIdRebuildErrors,
    PostApiDiscordByGuildIdRebuildResponses,
    PostApiDiscordByGuildIdResponses,
    PostApiGamesByGameIdPlayersData,
    PostApiGamesByGameIdPlayersErrors,
    PostApiGamesByGameIdPlayersResponses,
    PostApiGamesByGameIdStartData,
    PostApiGamesByGameIdStartErrors,
    PostApiGamesByGameIdStartResponses,
    PostApiGamesLoadData,
    PostApiGamesLoadErrors,
    PostApiGamesLoadResponses
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> =
    Options2<TData, ThrowOnError>
    & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Deletes the town in the provided server
 *
 * Removes all roles, channels and categories associated with clocktower
 */
export const deleteApiDiscordByGuildId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiDiscordByGuildIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteApiDiscordByGuildIdResponses, DeleteApiDiscordByGuildIdErrors, ThrowOnError>({
        url: '/api/discord/{guildId}',
        ...options
    });
};

/**
 * Checks access to guild
 *
 * Checks if bot has access to the guild
 */
export const checkGuildApi = <ThrowOnError extends boolean = false>(options: Options<CheckGuildApiData, ThrowOnError>) => {
    return (options.client ?? client).get<CheckGuildApiResponses, CheckGuildApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}',
        ...options
    });
};

/**
 * Creates the town in the provided server
 *
 * Creates the roles, categories and channels required for clocktower
 */
export const postApiDiscordByGuildId = <ThrowOnError extends boolean = false>(options: Options<PostApiDiscordByGuildIdData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiDiscordByGuildIdResponses, PostApiDiscordByGuildIdErrors, ThrowOnError>({
        url: '/api/discord/{guildId}',
        ...options
    });
};

/**
 * Get occupancy of town
 *
 * Gets user presense in the town
 */
export const getApiDiscordByGuildIdOccupancy = <ThrowOnError extends boolean = false>(options: Options<GetApiDiscordByGuildIdOccupancyData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiDiscordByGuildIdOccupancyResponses, GetApiDiscordByGuildIdOccupancyErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/occupancy',
        ...options
    });
};

/**
 * Rebuild town
 *
 * Rebuilds the town including roles, categories and channels
 */
export const postApiDiscordByGuildIdRebuild = <ThrowOnError extends boolean = false>(options: Options<PostApiDiscordByGuildIdRebuildData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiDiscordByGuildIdRebuildResponses, PostApiDiscordByGuildIdRebuildErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/rebuild',
        ...options
    });
};

/**
 * Toggles the storyteller role for a user
 *
 * Adds or removes the storyteller role from the specified user
 */
export const postApiDiscordByGuildIdByUserId = <ThrowOnError extends boolean = false>(options: Options<PostApiDiscordByGuildIdByUserIdData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiDiscordByGuildIdByUserIdResponses, PostApiDiscordByGuildIdByUserIdErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/{userId}',
        ...options
    });
};

/**
 * Get status of town
 *
 * Gets if the town exists in a valid state
 */
export const getApiDiscordByGuildIdStatus = <ThrowOnError extends boolean = false>(options: Options<GetApiDiscordByGuildIdStatusData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiDiscordByGuildIdStatusResponses, GetApiDiscordByGuildIdStatusErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/status',
        ...options
    });
};

/**
 * Add player to game
 */
export const postApiGamesByGameIdPlayers = <ThrowOnError extends boolean = false>(options: Options<PostApiGamesByGameIdPlayersData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiGamesByGameIdPlayersResponses, PostApiGamesByGameIdPlayersErrors, ThrowOnError>({
        url: '/api/games/{gameId}/players',
        ...options
    });
};

/**
 * Deletes a game by id
 */
export const deleteApiGamesByGameIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGamesByGameIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteApiGamesByGameIdDeleteResponses, DeleteApiGamesByGameIdDeleteErrors, ThrowOnError>({
        url: '/api/games/{gameId}/delete',
        ...options
    });
};

/**
 * Get the game state by id
 */
export const getApiGamesByGameId = <ThrowOnError extends boolean = false>(options: Options<GetApiGamesByGameIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiGamesByGameIdResponses, GetApiGamesByGameIdErrors, ThrowOnError>({
        url: '/api/games/{gameId}',
        ...options
    });
};

/**
 * Gets all games
 */
export const getApiGames = <ThrowOnError extends boolean = false>(options?: Options<GetApiGamesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiGamesResponses, GetApiGamesErrors, ThrowOnError>({
        url: '/api/games',
        ...options
    });
};

/**
 * Loads dummy data from saved json file
 */
export const postApiGamesLoad = <ThrowOnError extends boolean = false>(options?: Options<PostApiGamesLoadData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiGamesLoadResponses, PostApiGamesLoadErrors, ThrowOnError>({
        url: '/api/games/load',
        ...options
    });
};

/**
 * Starts new game state for id
 */
export const postApiGamesByGameIdStart = <ThrowOnError extends boolean = false>(options: Options<PostApiGamesByGameIdStartData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiGamesByGameIdStartResponses, PostApiGamesByGameIdStartErrors, ThrowOnError>({
        url: '/api/games/{gameId}/start',
        ...options
    });
};

/**
 * Return all roles
 *
 * Filter roles by edition and/or role type
 */
export const getApiRoles = <ThrowOnError extends boolean = false>(options?: Options<GetApiRolesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiRolesResponses, unknown, ThrowOnError>({
        url: '/api/roles',
        ...options
    });
};
