// This file is auto-generated by @hey-api/openapi-ts

import type {
    Client,
    Options as Options2,
    TDataShape
} from './client';
import {
    client
} from './client.gen';
import type {
    AddPlayerToGameApiData,
    AddPlayerToGameApiErrors,
    AddPlayerToGameApiResponses,
    CheckGuildApiData,
    CheckGuildApiErrors,
    CheckGuildApiResponses,
    CreateTownApiData,
    CreateTownApiErrors,
    CreateTownApiResponses,
    DeleteGameApiData,
    DeleteGameApiErrors,
    DeleteGameApiResponses,
    DeleteTownApiData,
    DeleteTownApiErrors,
    DeleteTownApiResponses,
    GetAuthDataApiData,
    GetAuthDataApiErrors,
    GetAuthDataApiResponses,
    GetGameApiData,
    GetGameApiErrors,
    GetGameApiResponses,
    GetGamesApiData,
    GetGamesApiErrors,
    GetGamesApiResponses,
    GetRolesApiData,
    GetRolesApiResponses,
    GetTownOccupancyApiData,
    GetTownOccupancyApiErrors,
    GetTownOccupancyApiResponses,
    GetTownStatusApiData,
    GetTownStatusApiErrors,
    GetTownStatusApiResponses,
    HandleDiscordCallbackApiData,
    HandleDiscordCallbackApiErrors,
    HandleDiscordCallbackApiResponses,
    InitiateDiscordAuthApiData,
    InitiateDiscordAuthApiErrors,
    LoadDummyGamesApiData,
    LoadDummyGamesApiErrors,
    LoadDummyGamesApiResponses,
    MoveUserToChannelApiData,
    MoveUserToChannelApiErrors,
    MoveUserToChannelApiResponses,
    RebuildTownApiData,
    RebuildTownApiErrors,
    RebuildTownApiResponses,
    StartGameApiData,
    StartGameApiErrors,
    StartGameApiResponses,
    ToggleStoryTellerApiData,
    ToggleStoryTellerApiErrors,
    ToggleStoryTellerApiResponses
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Initiate Discord OAuth
 *
 * Redirects user to Discord for OAuth authentication
 */
export const initiateDiscordAuthApi = <ThrowOnError extends boolean = false>(options?: Options<InitiateDiscordAuthApiData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, InitiateDiscordAuthApiErrors, ThrowOnError>({
        url: '/api/discord/auth',
        ...options
    });
};

/**
 * Handle Discord OAuth callback
 *
 * Handles the callback from Discord OAuth
 */
export const handleDiscordCallbackApi = <ThrowOnError extends boolean = false>(options?: Options<HandleDiscordCallbackApiData, ThrowOnError>) => {
    return (options?.client ?? client).get<HandleDiscordCallbackApiResponses, HandleDiscordCallbackApiErrors, ThrowOnError>({
        url: '/api/discord/auth/callback',
        ...options
    });
};

/**
 * Get temporary auth data
 *
 * Retrieves temporary authentication data by key
 */
export const getAuthDataApi = <ThrowOnError extends boolean = false>(options: Options<GetAuthDataApiData, ThrowOnError>) => {
    return (options.client ?? client).get<GetAuthDataApiResponses, GetAuthDataApiErrors, ThrowOnError>({
        url: '/api/discord/auth/data/{key}',
        ...options
    });
};

/**
 * Deletes the town in the provided server
 *
 * Removes all roles, channels and categories associated with clocktower
 */
export const deleteTownApi = <ThrowOnError extends boolean = false>(options: Options<DeleteTownApiData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteTownApiResponses, DeleteTownApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}',
        ...options
    });
};

/**
 * Checks access to guild
 *
 * Checks if bot has access to the guild
 */
export const checkGuildApi = <ThrowOnError extends boolean = false>(options: Options<CheckGuildApiData, ThrowOnError>) => {
    return (options.client ?? client).get<CheckGuildApiResponses, CheckGuildApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}',
        ...options
    });
};

/**
 * Creates the town in the provided server
 *
 * Creates the roles, categories and channels required for clocktower
 */
export const createTownApi = <ThrowOnError extends boolean = false>(options: Options<CreateTownApiData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateTownApiResponses, CreateTownApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}',
        ...options
    });
};

/**
 * Get occupancy of town
 *
 * Gets user presense in the town
 */
export const getTownOccupancyApi = <ThrowOnError extends boolean = false>(options: Options<GetTownOccupancyApiData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTownOccupancyApiResponses, GetTownOccupancyApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/occupancy',
        ...options
    });
};

/**
 * Get status of town
 *
 * Gets if the town exists in a valid state
 */
export const getTownStatusApi = <ThrowOnError extends boolean = false>(options: Options<GetTownStatusApiData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTownStatusApiResponses, GetTownStatusApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/status',
        ...options
    });
};

/**
 * Moves the user to the specified channel
 *
 * Moves the user to the specified channel
 */
export const moveUserToChannelApi = <ThrowOnError extends boolean = false>(options: Options<MoveUserToChannelApiData, ThrowOnError>) => {
    return (options.client ?? client).post<MoveUserToChannelApiResponses, MoveUserToChannelApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/{userId}/{channelId}',
        ...options
    });
};

/**
 * Rebuild town
 *
 * Rebuilds the town including roles, categories and channels
 */
export const rebuildTownApi = <ThrowOnError extends boolean = false>(options: Options<RebuildTownApiData, ThrowOnError>) => {
    return (options.client ?? client).post<RebuildTownApiResponses, RebuildTownApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/rebuild',
        ...options
    });
};

/**
 * Toggles the storyteller role for a user
 *
 * Adds or removes the storyteller role from the specified user
 */
export const toggleStoryTellerApi = <ThrowOnError extends boolean = false>(options: Options<ToggleStoryTellerApiData, ThrowOnError>) => {
    return (options.client ?? client).post<ToggleStoryTellerApiResponses, ToggleStoryTellerApiErrors, ThrowOnError>({
        url: '/api/discord/{guildId}/{userId}',
        ...options
    });
};

/**
 * Add player to game
 */
export const addPlayerToGameApi = <ThrowOnError extends boolean = false>(options: Options<AddPlayerToGameApiData, ThrowOnError>) => {
    return (options.client ?? client).post<AddPlayerToGameApiResponses, AddPlayerToGameApiErrors, ThrowOnError>({
        url: '/api/games/{gameId}/players',
        ...options
    });
};

/**
 * Deletes a game by id
 */
export const deleteGameApi = <ThrowOnError extends boolean = false>(options: Options<DeleteGameApiData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteGameApiResponses, DeleteGameApiErrors, ThrowOnError>({
        url: '/api/games/{gameId}/delete',
        ...options
    });
};

/**
 * Get the game state by id
 */
export const getGameApi = <ThrowOnError extends boolean = false>(options: Options<GetGameApiData, ThrowOnError>) => {
    return (options.client ?? client).get<GetGameApiResponses, GetGameApiErrors, ThrowOnError>({
        url: '/api/games/{gameId}',
        ...options
    });
};

/**
 * Gets all games
 */
export const getGamesApi = <ThrowOnError extends boolean = false>(options?: Options<GetGamesApiData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetGamesApiResponses, GetGamesApiErrors, ThrowOnError>({
        url: '/api/games',
        ...options
    });
};

/**
 * Loads dummy data from saved json file
 */
export const loadDummyGamesApi = <ThrowOnError extends boolean = false>(options?: Options<LoadDummyGamesApiData, ThrowOnError>) => {
    return (options?.client ?? client).post<LoadDummyGamesApiResponses, LoadDummyGamesApiErrors, ThrowOnError>({
        url: '/api/games/load',
        ...options
    });
};

/**
 * Starts new game state for id
 */
export const startGameApi = <ThrowOnError extends boolean = false>(options: Options<StartGameApiData, ThrowOnError>) => {
    return (options.client ?? client).post<StartGameApiResponses, StartGameApiErrors, ThrowOnError>({
        url: '/api/games/{gameId}/start',
        ...options
    });
};

/**
 * Return all roles
 *
 * Filter roles by edition and/or role type
 */
export const getRolesApi = <ThrowOnError extends boolean = false>(options?: Options<GetRolesApiData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetRolesApiResponses, unknown, ThrowOnError>({
        url: '/api/roles',
        ...options
    });
};
