// This file is auto-generated by @hey-api/openapi-ts

import type {
    AddPlayerToGameApiResponse,
    CheckGuildApiResponse,
    GetAuthDataApiResponse,
    GetGameApiResponse,
    GetGamesApiResponse,
    GetRolesApiResponse,
    GetTownOccupancyApiResponse,
    GetTownStatusApiResponse,
    StartGameApiResponse
} from './types.gen';

export const getAuthDataApiResponseTransformer = async (data: any): Promise<GetAuthDataApiResponse> => {
    data = clocktowerServerDiscordServicesMiniUserSchemaResponseTransformer(data);
    return data;
};

export const checkGuildApiResponseTransformer = async (data: any): Promise<CheckGuildApiResponse> => {
    data = clocktowerServerDiscordEndpointsCheckGuildResponseSchemaResponseTransformer(data);
    return data;
};

const clocktowerServerDiscordServicesTownOccupantsSchemaResponseTransformer = (data: any) => {
    if (data.channelCategories) {
        data.channelCategories = data.channelCategories.map((item: any) => {
            return clocktowerServerDiscordServicesMiniCategorySchemaResponseTransformer(item);
        });
    }
    return data;
};

const clocktowerServerDiscordServicesMiniCategorySchemaResponseTransformer = (data: any) => {
    if (data.channels) {
        data.channels = data.channels.map((item: any) => {
            return clocktowerServerDiscordServicesChannelOccupantsSchemaResponseTransformer(item);
        });
    }
    return data;
};

const clocktowerServerDiscordServicesChannelOccupantsSchemaResponseTransformer = (data: any) => {
    if (data.channel) {
        data.channel = clocktowerServerDiscordServicesMiniChannelSchemaResponseTransformer(data.channel);
    }
    if (data.occupants) {
        data.occupants = data.occupants.map((item: any) => {
            return clocktowerServerDiscordServicesMiniUserSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getTownOccupancyApiResponseTransformer = async (data: any): Promise<GetTownOccupancyApiResponse> => {
    data = clocktowerServerDiscordServicesTownOccupantsSchemaResponseTransformer(data);
    return data;
};

export const getTownStatusApiResponseTransformer = async (data: any): Promise<GetTownStatusApiResponse> => {
    data = clocktowerServerDiscordEndpointsGetTownStatusResponseSchemaResponseTransformer(data);
    return data;
};

export const addPlayerToGameApiResponseTransformer = async (data: any): Promise<AddPlayerToGameApiResponse> => {
    data = clocktowerServerDataTypesPlayerSchemaResponseTransformer(data);
    return data;
};

const clocktowerServerDataGameStateSchemaResponseTransformer = (data: any) => {
    if (data.players) {
        data.players = data.players.map((item: any) => {
            return clocktowerServerDataTypesPlayerSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getGameApiResponseTransformer = async (data: any): Promise<GetGameApiResponse> => {
    data = clocktowerServerDataGameStateSchemaResponseTransformer(data);
    return data;
};

export const getGamesApiResponseTransformer = async (data: any): Promise<GetGamesApiResponse> => {
    data = data.map((item: any) => {
        return clocktowerServerDataGameStateSchemaResponseTransformer(item);
    });
    return data;
};

export const startGameApiResponseTransformer = async (data: any): Promise<StartGameApiResponse> => {
    data = clocktowerServerDataGameStateSchemaResponseTransformer(data);
    return data;
};

const clocktowerServerRolesEndpointsGetRolesResponseSchemaResponseTransformer = (data: any) => {
    if (data.roles) {
        data.roles = data.roles.map((item: any) => {
            return clocktowerServerDataTypesRoleRoleSchemaResponseTransformer(item);
        });
    }
    return data;
};

const clocktowerServerDataTypesRoleRoleSchemaResponseTransformer = (data: any) => {
    if (data.type) {
        data.type = clocktowerServerDataTypesEnumRoleTypeSchemaResponseTransformer(data.type);
    }
    if (data.edition) {
        data.edition = clocktowerServerDataTypesEnumEditionSchemaResponseTransformer(data.edition);
    }
    return data;
};

export const getRolesApiResponseTransformer = async (data: any): Promise<GetRolesApiResponse> => {
    data = clocktowerServerRolesEndpointsGetRolesResponseSchemaResponseTransformer(data);
    return data;
};
