// This file is auto-generated by @hey-api/openapi-ts

import type {
    CheckGuildApiResponse,
    GetApiDiscordByGuildIdOccupancyResponse,
    GetApiDiscordByGuildIdStatusResponse,
    GetApiGamesByGameIdResponse,
    GetApiGamesResponse,
    GetApiRolesResponse,
    PostApiGamesByGameIdPlayersResponse,
    PostApiGamesByGameIdStartResponse
} from './types.gen';

export const checkGuildApiResponseTransformer = async (data: any): Promise<CheckGuildApiResponse> => {
    data = clocktowerServerDiscordEndpointsCheckGuildResponseSchemaResponseTransformer(data);
    return data;
};

const clocktowerServerDiscordServicesTownOccupantsSchemaResponseTransformer = (data: any) => {
    if (data.channelCategories) {
        data.channelCategories = data.channelCategories.map((item: any) => {
            return clocktowerServerDiscordServicesMiniCategorySchemaResponseTransformer(item);
        });
    }
    return data;
};

const clocktowerServerDiscordServicesMiniCategorySchemaResponseTransformer = (data: any) => {
    if (data.id) {
        data.id = BigInt(data.id.toString());
    }
    if (data.channels) {
        data.channels = data.channels.map((item: any) => {
            return clocktowerServerDiscordServicesChannelOccupantsSchemaResponseTransformer(item);
        });
    }
    return data;
};

const clocktowerServerDiscordServicesChannelOccupantsSchemaResponseTransformer = (data: any) => {
    if (data.channel) {
        data.channel = clocktowerServerDiscordServicesMiniChannelSchemaResponseTransformer(data.channel);
    }
    if (data.occupants) {
        data.occupants = data.occupants.map((item: any) => {
            return clocktowerServerDiscordServicesMiniUserSchemaResponseTransformer(item);
        });
    }
    return data;
};

const clocktowerServerDiscordServicesMiniChannelSchemaResponseTransformer = (data: any) => {
    if (data.id) {
        data.id = BigInt(data.id.toString());
    }
    return data;
};

const clocktowerServerDiscordServicesMiniUserSchemaResponseTransformer = (data: any) => {
    if (data.id) {
        data.id = BigInt(data.id.toString());
    }
    return data;
};

export const getApiDiscordByGuildIdOccupancyResponseTransformer = async (data: any): Promise<GetApiDiscordByGuildIdOccupancyResponse> => {
    data = clocktowerServerDiscordServicesTownOccupantsSchemaResponseTransformer(data);
    return data;
};

export const getApiDiscordByGuildIdStatusResponseTransformer = async (data: any): Promise<GetApiDiscordByGuildIdStatusResponse> => {
    data = clocktowerServerDiscordEndpointsTownStatusTownExistsResponseSchemaResponseTransformer(data);
    return data;
};

export const postApiGamesByGameIdPlayersResponseTransformer = async (data: any): Promise<PostApiGamesByGameIdPlayersResponse> => {
    data = clocktowerServerDataTypesPlayerSchemaResponseTransformer(data);
    return data;
};

const clocktowerServerDataGameStateSchemaResponseTransformer = (data: any) => {
    if (data.players) {
        data.players = data.players.map((item: any) => {
            return clocktowerServerDataTypesPlayerSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const getApiGamesByGameIdResponseTransformer = async (data: any): Promise<GetApiGamesByGameIdResponse> => {
    data = clocktowerServerDataGameStateSchemaResponseTransformer(data);
    return data;
};

export const getApiGamesResponseTransformer = async (data: any): Promise<GetApiGamesResponse> => {
    data = data.map((item: any) => {
        return clocktowerServerDataGameStateSchemaResponseTransformer(item);
    });
    return data;
};

export const postApiGamesByGameIdStartResponseTransformer = async (data: any): Promise<PostApiGamesByGameIdStartResponse> => {
    data = clocktowerServerDataGameStateSchemaResponseTransformer(data);
    return data;
};

const clocktowerServerRolesEndpointsGetRolesResponseSchemaResponseTransformer = (data: any) => {
    if (data.roles) {
        data.roles = data.roles.map((item: any) => {
            return clocktowerServerDataTypesRoleRoleSchemaResponseTransformer(item);
        });
    }
    return data;
};

const clocktowerServerDataTypesRoleRoleSchemaResponseTransformer = (data: any) => {
    if (data.type) {
        data.type = clocktowerServerDataTypesEnumRoleTypeSchemaResponseTransformer(data.type);
    }
    if (data.edition) {
        data.edition = clocktowerServerDataTypesEnumEditionSchemaResponseTransformer(data.edition);
    }
    return data;
};

export const getApiRolesResponseTransformer = async (data: any): Promise<GetApiRolesResponse> => {
    data = clocktowerServerRolesEndpointsGetRolesResponseSchemaResponseTransformer(data);
    return data;
};
