// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5120' | (string & {});
};

export type ClocktowerServerDataGameState = {
    id?: string | null;
    players?: Array<ClocktowerServerDataTypesPlayer> | null;
    maxPlayers?: number;
    readonly isFull?: boolean;
};

export type ClocktowerServerDataTypesEnumEdition =
    'TroubleBrewing'
    | 'SectsAndViolets'
    | 'BadMoonRising'
    | 'Experimental';

export type ClocktowerServerDataTypesEnumRoleType =
    'Townsfolk'
    | 'Outsider'
    | 'Minion'
    | 'Demon'
    | 'Traveller';

export type ClocktowerServerDataTypesPlayer = {
    id?: number;
    name?: string | null;
};

export type ClocktowerServerDataTypesRoleRole = {
    name?: string | null;
    description?: string | null;
    type?: ClocktowerServerDataTypesEnumRoleType;
    edition?: ClocktowerServerDataTypesEnumEdition;
};

export type ClocktowerServerDiscordEndpointsCheckGuildResponse = {
    valid?: boolean;
    name?: string | null;
    message?: string | null;
};

export type ClocktowerServerDiscordEndpointsTownStatusTownExistsResponse = {
    exists?: boolean;
    message?: string | null;
};

export type ClocktowerServerDiscordServicesChannelOccupants = {
    channel?: ClocktowerServerDiscordServicesMiniChannel;
    occupants?: Array<ClocktowerServerDiscordServicesMiniUser> | null;
};

export type ClocktowerServerDiscordServicesMiniCategory = {
    id?: bigint;
    name?: string | null;
    channels?: Array<ClocktowerServerDiscordServicesChannelOccupants> | null;
};

export type ClocktowerServerDiscordServicesMiniChannel = {
    id?: bigint;
    name?: string | null;
};

export type ClocktowerServerDiscordServicesMiniUser = {
    id?: bigint;
    name?: string | null;
};

export type ClocktowerServerDiscordServicesTownOccupants = {
    channelCategories?: Array<ClocktowerServerDiscordServicesMiniCategory> | null;
    readonly userCount?: number;
};

export type ClocktowerServerRolesEndpointsGetRolesResponse = {
    roles?: Array<ClocktowerServerDataTypesRoleRole> | null;
};

export type MicrosoftAspNetCoreHttpHttpValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | {
        [key: string]: Array<string>;
    } | null | undefined;
};

export type ClocktowerServerDataGameStateWritable = {
    id?: string | null;
    players?: Array<ClocktowerServerDataTypesPlayer> | null;
    maxPlayers?: number;
};

export type ClocktowerServerDiscordServicesTownOccupantsWritable = {
    channelCategories?: Array<ClocktowerServerDiscordServicesMiniCategory> | null;
};

export type DeleteApiDiscordByGuildIdData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}';
};

export type DeleteApiDiscordByGuildIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type DeleteApiDiscordByGuildIdError = DeleteApiDiscordByGuildIdErrors[keyof DeleteApiDiscordByGuildIdErrors];

export type DeleteApiDiscordByGuildIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type DeleteApiDiscordByGuildIdResponse = DeleteApiDiscordByGuildIdResponses[keyof DeleteApiDiscordByGuildIdResponses];

export type CheckGuildApiData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}';
};

export type CheckGuildApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type CheckGuildApiError = CheckGuildApiErrors[keyof CheckGuildApiErrors];

export type CheckGuildApiResponses = {
    /**
     * OK
     */
    200: ClocktowerServerDiscordEndpointsCheckGuildResponse;
};

export type CheckGuildApiResponse = CheckGuildApiResponses[keyof CheckGuildApiResponses];

export type PostApiDiscordByGuildIdData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}';
};

export type PostApiDiscordByGuildIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type PostApiDiscordByGuildIdError = PostApiDiscordByGuildIdErrors[keyof PostApiDiscordByGuildIdErrors];

export type PostApiDiscordByGuildIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiDiscordByGuildIdResponse = PostApiDiscordByGuildIdResponses[keyof PostApiDiscordByGuildIdResponses];

export type GetApiDiscordByGuildIdOccupancyData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}/occupancy';
};

export type GetApiDiscordByGuildIdOccupancyErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type GetApiDiscordByGuildIdOccupancyError = GetApiDiscordByGuildIdOccupancyErrors[keyof GetApiDiscordByGuildIdOccupancyErrors];

export type GetApiDiscordByGuildIdOccupancyResponses = {
    /**
     * OK
     */
    200: ClocktowerServerDiscordServicesTownOccupants;
};

export type GetApiDiscordByGuildIdOccupancyResponse = GetApiDiscordByGuildIdOccupancyResponses[keyof GetApiDiscordByGuildIdOccupancyResponses];

export type PostApiDiscordByGuildIdRebuildData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}/rebuild';
};

export type PostApiDiscordByGuildIdRebuildErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type PostApiDiscordByGuildIdRebuildError = PostApiDiscordByGuildIdRebuildErrors[keyof PostApiDiscordByGuildIdRebuildErrors];

export type PostApiDiscordByGuildIdRebuildResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiDiscordByGuildIdRebuildResponse = PostApiDiscordByGuildIdRebuildResponses[keyof PostApiDiscordByGuildIdRebuildResponses];

export type PostApiDiscordByGuildIdByUserIdData = {
    body?: never;
    path: {
        guildId: bigint;
        userId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}/{userId}';
};

export type PostApiDiscordByGuildIdByUserIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type PostApiDiscordByGuildIdByUserIdError = PostApiDiscordByGuildIdByUserIdErrors[keyof PostApiDiscordByGuildIdByUserIdErrors];

export type PostApiDiscordByGuildIdByUserIdResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiDiscordByGuildIdByUserIdResponse = PostApiDiscordByGuildIdByUserIdResponses[keyof PostApiDiscordByGuildIdByUserIdResponses];

export type GetApiDiscordByGuildIdStatusData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}/status';
};

export type GetApiDiscordByGuildIdStatusErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type GetApiDiscordByGuildIdStatusError = GetApiDiscordByGuildIdStatusErrors[keyof GetApiDiscordByGuildIdStatusErrors];

export type GetApiDiscordByGuildIdStatusResponses = {
    /**
     * OK
     */
    200: ClocktowerServerDiscordEndpointsTownStatusTownExistsResponse;
};

export type GetApiDiscordByGuildIdStatusResponse = GetApiDiscordByGuildIdStatusResponses[keyof GetApiDiscordByGuildIdStatusResponses];

export type PostApiGamesByGameIdPlayersData = {
    body?: never;
    path: {
        gameId: string;
    };
    query: {
        PlayerName: string;
    };
    url: '/api/games/{gameId}/players';
};

export type PostApiGamesByGameIdPlayersErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
    /**
     * Conflict
     */
    409: string;
};

export type PostApiGamesByGameIdPlayersError = PostApiGamesByGameIdPlayersErrors[keyof PostApiGamesByGameIdPlayersErrors];

export type PostApiGamesByGameIdPlayersResponses = {
    /**
     * Created
     */
    201: ClocktowerServerDataTypesPlayer;
};

export type PostApiGamesByGameIdPlayersResponse = PostApiGamesByGameIdPlayersResponses[keyof PostApiGamesByGameIdPlayersResponses];

export type DeleteApiGamesByGameIdDeleteData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/games/{gameId}/delete';
};

export type DeleteApiGamesByGameIdDeleteErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type DeleteApiGamesByGameIdDeleteError = DeleteApiGamesByGameIdDeleteErrors[keyof DeleteApiGamesByGameIdDeleteErrors];

export type DeleteApiGamesByGameIdDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGamesByGameIdData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/games/{gameId}';
};

export type GetApiGamesByGameIdErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type GetApiGamesByGameIdError = GetApiGamesByGameIdErrors[keyof GetApiGamesByGameIdErrors];

export type GetApiGamesByGameIdResponses = {
    /**
     * OK
     */
    200: ClocktowerServerDataGameState;
};

export type GetApiGamesByGameIdResponse = GetApiGamesByGameIdResponses[keyof GetApiGamesByGameIdResponses];

export type GetApiGamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/games';
};

export type GetApiGamesErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type GetApiGamesError = GetApiGamesErrors[keyof GetApiGamesErrors];

export type GetApiGamesResponses = {
    /**
     * OK
     */
    200: Array<ClocktowerServerDataGameState>;
};

export type GetApiGamesResponse = GetApiGamesResponses[keyof GetApiGamesResponses];

export type PostApiGamesLoadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/games/load';
};

export type PostApiGamesLoadErrors = {
    /**
     * Bad Request
     */
    400: string;
};

export type PostApiGamesLoadError = PostApiGamesLoadErrors[keyof PostApiGamesLoadErrors];

export type PostApiGamesLoadResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostApiGamesLoadResponse = PostApiGamesLoadResponses[keyof PostApiGamesLoadResponses];

export type PostApiGamesByGameIdStartData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/games/{gameId}/start';
};

export type PostApiGamesByGameIdStartErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
};

export type PostApiGamesByGameIdStartError = PostApiGamesByGameIdStartErrors[keyof PostApiGamesByGameIdStartErrors];

export type PostApiGamesByGameIdStartResponses = {
    /**
     * Created
     */
    201: ClocktowerServerDataGameState;
};

export type PostApiGamesByGameIdStartResponse = PostApiGamesByGameIdStartResponses[keyof PostApiGamesByGameIdStartResponses];

export type GetApiRolesData = {
    body?: never;
    path?: never;
    query?: {
        RoleType?: ClocktowerServerDataTypesEnumRoleType;
        Edition?: ClocktowerServerDataTypesEnumEdition;
    };
    url: '/api/roles';
};

export type GetApiRolesResponses = {
    /**
     * OK
     */
    200: ClocktowerServerRolesEndpointsGetRolesResponse;
};

export type GetApiRolesResponse = GetApiRolesResponses[keyof GetApiRolesResponses];
