// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5120' | (string & {});
};

export type ClocktowerServerDataGameState = {
    id?: string | null;
    players?: Array<ClocktowerServerDataTypesPlayer> | null;
    maxPlayers?: number;
    readonly isFull?: boolean;
};

export type ClocktowerServerDataTypesEnumEdition =
    'TroubleBrewing'
    | 'SectsAndViolets'
    | 'BadMoonRising'
    | 'Experimental';

export type ClocktowerServerDataTypesEnumRoleType =
    'Townsfolk'
    | 'Outsider'
    | 'Minion'
    | 'Demon'
    | 'Traveller';

export type ClocktowerServerDataTypesPlayer = {
    id?: number;
    name?: string | null;
};

export type ClocktowerServerDataTypesRoleRole = {
    name?: string | null;
    description?: string | null;
    type?: ClocktowerServerDataTypesEnumRoleType;
    edition?: ClocktowerServerDataTypesEnumEdition;
};

export type ClocktowerServerDiscordEndpointsCheckGuildResponse = {
    valid?: boolean;
    name?: string | null;
    message?: string | null;
};

export type ClocktowerServerDiscordEndpointsGetTownStatusTownExistsResponse = {
    exists?: boolean;
    message?: string | null;
};

export type ClocktowerServerDiscordServicesChannelOccupants = {
    channel?: ClocktowerServerDiscordServicesMiniChannel;
    occupants?: Array<ClocktowerServerDiscordServicesMiniUser> | null;
};

export type ClocktowerServerDiscordServicesMiniCategory = {
    id?: bigint;
    name?: string | null;
    channels?: Array<ClocktowerServerDiscordServicesChannelOccupants> | null;
};

export type ClocktowerServerDiscordServicesMiniChannel = {
    id?: bigint;
    name?: string | null;
};

export type ClocktowerServerDiscordServicesMiniUser = {
    id?: bigint;
    name?: string | null;
};

export type ClocktowerServerDiscordServicesTownOccupants = {
    channelCategories?: Array<ClocktowerServerDiscordServicesMiniCategory> | null;
    readonly userCount?: number;
};

export type ClocktowerServerRolesEndpointsGetRolesResponse = {
    roles?: Array<ClocktowerServerDataTypesRoleRole> | null;
};

export type MicrosoftAspNetCoreHttpHttpValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | {
        [key: string]: Array<string>;
    } | null | undefined;
};

export type ClocktowerServerDataGameStateWritable = {
    id?: string | null;
    players?: Array<ClocktowerServerDataTypesPlayer> | null;
    maxPlayers?: number;
};

export type ClocktowerServerDiscordServicesTownOccupantsWritable = {
    channelCategories?: Array<ClocktowerServerDiscordServicesMiniCategory> | null;
};

export type DeleteTownApiData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}';
};

export type DeleteTownApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type DeleteTownApiError = DeleteTownApiErrors[keyof DeleteTownApiErrors];

export type DeleteTownApiResponses = {
    /**
     * OK
     */
    200: string;
};

export type DeleteTownApiResponse = DeleteTownApiResponses[keyof DeleteTownApiResponses];

export type CheckGuildApiData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}';
};

export type CheckGuildApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type CheckGuildApiError = CheckGuildApiErrors[keyof CheckGuildApiErrors];

export type CheckGuildApiResponses = {
    /**
     * OK
     */
    200: ClocktowerServerDiscordEndpointsCheckGuildResponse;
};

export type CheckGuildApiResponse = CheckGuildApiResponses[keyof CheckGuildApiResponses];

export type CreateTownApiData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}';
};

export type CreateTownApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type CreateTownApiError = CreateTownApiErrors[keyof CreateTownApiErrors];

export type CreateTownApiResponses = {
    /**
     * OK
     */
    200: string;
};

export type CreateTownApiResponse = CreateTownApiResponses[keyof CreateTownApiResponses];

export type GetTownOccupancyApiData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}/occupancy';
};

export type GetTownOccupancyApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type GetTownOccupancyApiError = GetTownOccupancyApiErrors[keyof GetTownOccupancyApiErrors];

export type GetTownOccupancyApiResponses = {
    /**
     * OK
     */
    200: ClocktowerServerDiscordServicesTownOccupants;
};

export type GetTownOccupancyApiResponse = GetTownOccupancyApiResponses[keyof GetTownOccupancyApiResponses];

export type GetTownStatusApiData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}/status';
};

export type GetTownStatusApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type GetTownStatusApiError = GetTownStatusApiErrors[keyof GetTownStatusApiErrors];

export type GetTownStatusApiResponses = {
    /**
     * OK
     */
    200: ClocktowerServerDiscordEndpointsGetTownStatusTownExistsResponse;
};

export type GetTownStatusApiResponse = GetTownStatusApiResponses[keyof GetTownStatusApiResponses];

export type RebuildTownApiData = {
    body?: never;
    path: {
        guildId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}/rebuild';
};

export type RebuildTownApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type RebuildTownApiError = RebuildTownApiErrors[keyof RebuildTownApiErrors];

export type RebuildTownApiResponses = {
    /**
     * OK
     */
    200: string;
};

export type RebuildTownApiResponse = RebuildTownApiResponses[keyof RebuildTownApiResponses];

export type ToggleStoryTellerApiData = {
    body?: never;
    path: {
        guildId: bigint;
        userId: bigint;
    };
    query?: never;
    url: '/api/discord/{guildId}/{userId}';
};

export type ToggleStoryTellerApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
};

export type ToggleStoryTellerApiError = ToggleStoryTellerApiErrors[keyof ToggleStoryTellerApiErrors];

export type ToggleStoryTellerApiResponses = {
    /**
     * OK
     */
    200: string;
};

export type ToggleStoryTellerApiResponse = ToggleStoryTellerApiResponses[keyof ToggleStoryTellerApiResponses];

export type AddPlayerToGameApiData = {
    body?: never;
    path: {
        gameId: string;
    };
    query: {
        PlayerName: string;
    };
    url: '/api/games/{gameId}/players';
};

export type AddPlayerToGameApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: string;
    /**
     * Conflict
     */
    409: string;
};

export type AddPlayerToGameApiError = AddPlayerToGameApiErrors[keyof AddPlayerToGameApiErrors];

export type AddPlayerToGameApiResponses = {
    /**
     * Created
     */
    201: ClocktowerServerDataTypesPlayer;
};

export type AddPlayerToGameApiResponse = AddPlayerToGameApiResponses[keyof AddPlayerToGameApiResponses];

export type DeleteGameApiData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/games/{gameId}/delete';
};

export type DeleteGameApiErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type DeleteGameApiError = DeleteGameApiErrors[keyof DeleteGameApiErrors];

export type DeleteGameApiResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGameApiData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/games/{gameId}';
};

export type GetGameApiErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type GetGameApiError = GetGameApiErrors[keyof GetGameApiErrors];

export type GetGameApiResponses = {
    /**
     * OK
     */
    200: ClocktowerServerDataGameState;
};

export type GetGameApiResponse = GetGameApiResponses[keyof GetGameApiResponses];

export type GetGamesApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/games';
};

export type GetGamesApiErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type GetGamesApiError = GetGamesApiErrors[keyof GetGamesApiErrors];

export type GetGamesApiResponses = {
    /**
     * OK
     */
    200: Array<ClocktowerServerDataGameState>;
};

export type GetGamesApiResponse = GetGamesApiResponses[keyof GetGamesApiResponses];

export type LoadDummyGamesApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/games/load';
};

export type LoadDummyGamesApiErrors = {
    /**
     * Bad Request
     */
    400: string;
};

export type LoadDummyGamesApiError = LoadDummyGamesApiErrors[keyof LoadDummyGamesApiErrors];

export type LoadDummyGamesApiResponses = {
    /**
     * OK
     */
    200: string;
};

export type LoadDummyGamesApiResponse = LoadDummyGamesApiResponses[keyof LoadDummyGamesApiResponses];

export type StartGameApiData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/games/{gameId}/start';
};

export type StartGameApiErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreHttpHttpValidationProblemDetails;
};

export type StartGameApiError = StartGameApiErrors[keyof StartGameApiErrors];

export type StartGameApiResponses = {
    /**
     * Created
     */
    201: ClocktowerServerDataGameState;
};

export type StartGameApiResponse = StartGameApiResponses[keyof StartGameApiResponses];

export type GetRolesApiData = {
    body?: never;
    path?: never;
    query?: {
        RoleType?: ClocktowerServerDataTypesEnumRoleType;
        Edition?: ClocktowerServerDataTypesEnumEdition;
    };
    url: '/api/roles';
};

export type GetRolesApiResponses = {
    /**
     * OK
     */
    200: ClocktowerServerRolesEndpointsGetRolesResponse;
};

export type GetRolesApiResponse = GetRolesApiResponses[keyof GetRolesApiResponses];
